@startuml

    set namespaceSeparator \\

    skinparam {
        padding 2
        backgroundColor #222
        shadowing false

        classFontColor #eee
        classStereotypeFontColor #eee
        classBorderColor #111
        classFontSize 14
        ClassAttributeFontColor #eee
        ClassAttributeFontSize 13
        ClassAttributeIconSize 15

        PackageBackgroundColor #2c2c2c
        PackageBorderColor #111
        PackageFontColor #eee

        ArrowColor yellow
    }

    skinparam circled {
        CharacterFontColor black
        CharacterFontSize 18
        CharacterFontStyle plain
        CharacterRadius 12
    }


    skinparam <<public class>> {
        classBackgroundColor #004b00/#003b00
        classFontSize 16
    }

    skinparam <<private class>> {
        classBackgroundColor #5d0000/#4d0000
    }

    skinparam <<protected class>> {
        classBackgroundColor #d16300/#c15300
    }
@enduml
