@startuml

    set namespaceSeparator \\

    skinparam {
        padding 2
        backgroundColor #222
        shadowing false

        classFontColor #eee
        classStereotypeFontColor #eee
        classBorderColor #111
        classFontSize 14
        ClassAttributeFontColor #eee
        ClassAttributeFontSize 13
        ClassAttributeIconSize 15

        PackageBackgroundColor #2c2c2c
        PackageBorderColor #111
        PackageFontColor #eee

        ArrowColor yellow

        circledCharacterFontColor black
        circledCharacterFontSize 16
        circledCharacterFontStyle plain
        circledCharacterRadius 10

        packageStyle rectangle

        <<public class>>classBackgroundColor #004b00/#003b00
        <<public class>>classFontSize 16

        <<private class>>classBackgroundColor #5d0000/#4d0000

        <<protected class>>classBackgroundColor #d16300/#c15300

        <<abstract class>>classBorderColor #755800
    }

@enduml
